// packages/react/src/components/BalanceDisplay.tsx
import styles from '../styles/NFTJuiceWidget.module.css';

import React, {useState, useEffect} from 'react';
import classNames from "classnames";
import type {UserBalances, CollectionBalance, UserNFT} from '@nftjuice/sdk';

import {NFTList} from './NFTList.js';
import {useNFTJuice} from '../context/NFTJuiceContext.js';
import type {BalanceDisplayProps} from '../types.js';

export function BalanceDisplay({
                                   userAddress,
                                   collectionAddress,
                                   showAllCollections = true,
                                   className = '',
                                   view = 'grid',
                               }: BalanceDisplayProps) {
    const {sdk, wallet} = useNFTJuice();
    const [balances, setBalances] = useState<UserBalances | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string>('');

    const addressToQuery = userAddress || wallet.address;

    useEffect(() => {
        const loadBalances = async () => {
            if (!sdk || !addressToQuery) return;

            if (!collectionAddress) {
                setBalances({address: addressToQuery, collections: []});
                return;
            }

            setIsLoading(true);
            setError('');

            try {
                const userBalances = await sdk.getUserBalances(addressToQuery, [collectionAddress]);
                setBalances(userBalances);
            } catch (err: any) {
                setError(err.message || 'Failed to load balances');
            } finally {
                setIsLoading(false);
            }
        };

        loadBalances();
    }, [sdk, addressToQuery, collectionAddress]);

    if (!addressToQuery) {
        return (
            <div className={classNames(styles.container, className)}>
                <div className={styles.errorMessage}>No wallet address available</div>
            </div>
        );
    }

    if (isLoading) {
        return (
            <div className={classNames(styles.container, className)}>
                <div className={styles.loadingMessage}>Loading balances...</div>
            </div>
        );
    }

    if (error) {
        return (
            <div className={classNames(styles.container, className)}>
                <div className={styles.errorMessage}>{error}</div>
            </div>
        );
    }

    if (!balances) {
        return null;
    }

    const collectionsToShow = showAllCollections
        ? balances.collections
        : balances.collections.filter(
            (c: CollectionBalance) => c.collectionAddress.toLowerCase() === collectionAddress?.toLowerCase()
        );

    if (collectionsToShow.length === 0) {
        return (
            <div className={classNames(styles.container, className)}>
                <h3 className={styles.sectionTitle}>Your NFTJuice Balances</h3>
                <div className={styles.emptyMessage}>
                    No balances found for the specified collection(s).
                </div>
            </div>
        );
    }

    return (
        <div className={classNames(styles.container, className)}>
            <h3 className={styles.sectionTitle}>Your NFTJuice Balances</h3>
            <div className={styles.sectionDescription}>
                Address: {addressToQuery.slice(0, 6)}...{addressToQuery.slice(-4)}
            </div>

            <div className={classNames(styles.collections, styles.mt)}>
                {collectionsToShow.map((collection) => (
                    <CollectionBalanceCard key={collection.collectionAddress} collection={collection} view={view}/>
                ))}
            </div>
        </div>
    );
}

function CollectionBalanceCard({collection, view = 'grid'}: { collection: CollectionBalance, view: 'grid' | 'list' }) {
    const {sdk} = useNFTJuice();
    const [vaultNFTs, setVaultNFTs] = useState<UserNFT[]>([]);
    const [isLoadingNFTs, setIsLoadingNFTs] = useState(false);

    useEffect(() => {
        const loadVaultNFTs = async () => {
            if (!sdk || collection.bottleNFTs.length === 0) return;

            setIsLoadingNFTs(true);

            try {
                // Convert bottleNFTs to UserNFT format with metadata
                const vaultNFTsWithMetadata: UserNFT[] = [];

                for (const bottleNFT of collection.bottleNFTs) {
                    const metadata = await sdk.fetchNFTMetadata(bottleNFT.tokenUri || '');
                    vaultNFTsWithMetadata.push({
                        tokenId: bottleNFT.tokenId,
                        ...(bottleNFT.tokenUri && {tokenUri: bottleNFT.tokenUri}),
                        ...(metadata && {metadata}),
                        isInVault: true
                    });
                }

                setVaultNFTs(vaultNFTsWithMetadata);
            } catch (err) {
                console.error('Failed to load vault NFT metadata:', err);
            } finally {
                setIsLoadingNFTs(false);
            }
        };

        loadVaultNFTs();
    }, [sdk, collection.bottleNFTs]);

    return (
        <div className={styles.collectionCard}>
            <div className={classNames(styles.info, styles.collectionCardInfo)}>
                <h5 className={styles.sectionTitle}>
                    Collection: {collection.collectionAddress.slice(0, 6)}...{collection.collectionAddress.slice(-4)}
                </h5>

                <p><strong>Juice Balance:</strong> {parseFloat(collection.juiceBalance).toFixed(2)} Juice</p>
                <p><strong>NFTs in Vault:</strong> {collection.bottleNFTs.length} NFT(s)</p>
            </div>

            {collection.bottleNFTs.length > 0 && (
                <div>
                    <h5 className={styles.sectionTitle}>Your NFTs in Vault</h5>
                    <NFTList
                        nfts={vaultNFTs}
                        view={view}
                        layout="horizontal"
                        showStatus={false}
                        statusFilter="all"
                        loading={isLoadingNFTs}
                        emptyMessage="No NFT metadata available"
                    />
                </div>
            )}
        </div>
    );
}

// packages/angular/src/lib/components/balance-display/balance-display.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { UserBalances, CollectionBalance, UserNFT } from '@nftjuice/sdk';
import { NFTJuiceService } from '../../services/nft-juice.service';
import { WalletService } from '../../services/wallet.service';
import { NftListComponent } from '../nft-list/nft-list.component';
import type { ViewMode } from '../../types';

@Component({
    selector: 'nftjuice-balance-display',
    standalone: true,
    imports: [CommonModule, NftListComponent],
    templateUrl: './balance-display.component.html',
    styleUrls: ['../../styles/nft-juice.css'],
    encapsulation: ViewEncapsulation.Emulated
})
export class BalanceDisplayComponent implements OnInit {
    @Input() userAddress?: string;
    @Input() collectionAddress?: string;
    @Input() showAllCollections = true;
    @Input() view: ViewMode = 'grid';
    @Input() className = '';

    balances: UserBalances | null = null;
    isLoading = false;
    errorMessage = '';
    vaultNFTsMap: Map<string, UserNFT[]> = new Map();
    loadingNFTsMap: Map<string, boolean> = new Map();

    constructor(
        private nftJuiceService: NFTJuiceService,
        private walletService: WalletService
    ) {}

    ngOnInit(): void {
        this.loadBalances();
    }

    async loadBalances(): Promise<void> {
        const sdk = this.nftJuiceService.currentSdk;
        const addressToQuery = this.userAddress || this.walletService.currentWallet.address;

        if (!sdk || !addressToQuery) return;

        if (!this.collectionAddress) {
            this.balances = { address: addressToQuery, collections: [] };
            return;
        }

        this.isLoading = true;
        this.errorMessage = '';

        try {
            this.balances = await sdk.getUserBalances(addressToQuery, [this.collectionAddress]);

            // Load metadata for all collections
            if (this.balances) {
                for (const collection of this.balances.collections) {
                    await this.loadVaultNFTsForCollection(collection);
                }
            }
        } catch (err: any) {
            this.errorMessage = err.message || 'Failed to load balances';
        } finally {
            this.isLoading = false;
        }
    }

    async loadVaultNFTsForCollection(collection: CollectionBalance): Promise<void> {
        const sdk = this.nftJuiceService.currentSdk;
        if (!sdk || collection.bottleNFTs.length === 0) return;

        this.loadingNFTsMap.set(collection.collectionAddress, true);

        try {
            const vaultNFTsWithMetadata: UserNFT[] = [];

            for (const bottleNFT of collection.bottleNFTs) {
                const metadata = await sdk.fetchNFTMetadata(bottleNFT.tokenUri || '');
                vaultNFTsWithMetadata.push({
                    tokenId: bottleNFT.tokenId,
                    ...(bottleNFT.tokenUri && { tokenUri: bottleNFT.tokenUri }),
                    ...(metadata && { metadata }),
                    isInVault: true
                });
            }

            this.vaultNFTsMap.set(collection.collectionAddress, vaultNFTsWithMetadata);
        } catch (err) {
            console.error('Failed to load vault NFT metadata:', err);
        } finally {
            this.loadingNFTsMap.set(collection.collectionAddress, false);
        }
    }

    get addressToQuery(): string | undefined {
        return this.userAddress || this.walletService.currentWallet.address;
    }

    get collectionsToShow(): CollectionBalance[] {
        if (!this.balances) return [];

        return this.showAllCollections
            ? this.balances.collections
            : this.balances.collections.filter(
                (c: CollectionBalance) => c.collectionAddress.toLowerCase() === this.collectionAddress?.toLowerCase()
            );
    }

    getVaultNFTs(collection: CollectionBalance): UserNFT[] {
        return this.vaultNFTsMap.get(collection.collectionAddress) || [];
    }

    isLoadingNFTs(collection: CollectionBalance): boolean {
        return this.loadingNFTsMap.get(collection.collectionAddress) || false;
    }

    formatAddress(address: string): string {
        return `${address.slice(0, 6)}...${address.slice(-4)}`;
    }

    formatBalance(balance: string): string {
        return parseFloat(balance).toFixed(2);
    }
}

<div *ngIf="!addressToQuery" [class]="'container ' + className">
    <div class="errorMessage">No wallet address available</div>
</div>

<div *ngIf="isLoading && addressToQuery" [class]="'container ' + className">
    <div class="loadingMessage">Loading balances...</div>
</div>

<div *ngIf="errorMessage && addressToQuery" [class]="'container ' + className">
    <div class="errorMessage">{{ errorMessage }}</div>
</div>

<div *ngIf="!isLoading && !errorMessage && balances && collectionsToShow.length === 0 && addressToQuery" [class]="'container ' + className">
    <h3 class="sectionTitle">Your NFTJuice Balances</h3>
    <div class="emptyMessage">No balances found for the specified collection(s).</div>
</div>

<div *ngIf="!isLoading && !errorMessage && balances && collectionsToShow.length > 0 && addressToQuery" [class]="'container ' + className">
    <h3 class="sectionTitle">Your NFTJuice Balances</h3>
    <div class="sectionDescription">
        Address: {{ formatAddress(addressToQuery) }}
    </div>

    <div class="collections mt">
        <div *ngFor="let collection of collectionsToShow" class="collectionCard">
            <div class="collectionCardInfo">
                <h4 class="sectionTitle">
                    {{ formatAddress(collection.collectionAddress) }}
                </h4>
                <p><strong>Juice Balance:</strong> {{ formatBalance(collection.juiceBalance) }} Juice</p>
                <p><strong>Bottle NFTs:</strong> {{ collection.bottleNFTs.length }}</p>
            </div>

            <div *ngIf="collection.bottleNFTs.length === 0" class="emptyMessage mt">
                No Bottle NFTs
            </div>

            <div *ngIf="collection.bottleNFTs.length > 0">
                <nftjuice-nft-list
                    [nfts]="getVaultNFTs(collection)"
                    [view]="view"
                    [layout]="'horizontal'"
                    [loading]="isLoadingNFTs(collection)"
                    [emptyMessage]="'No NFT metadata available'">
                </nftjuice-nft-list>
            </div>
        </div>
    </div>
</div>
