// packages/angular/src/lib/components/nft-juice-widget/nft-juice-widget.component.ts
import { Component, Input, OnInit, OnDestroy, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subscription } from 'rxjs';
import { NETWORK_CONFIGS, type CollectionInfo } from '@nftjuice/sdk';
import { NFTJuiceService } from '../../services/nft-juice.service';
import { WalletService } from '../../services/wallet.service';
import { DepositNftComponent } from '../deposit-nft/deposit-nft.component';
import { WithdrawNftComponent } from '../withdraw-nft/withdraw-nft.component';
import { BalanceDisplayComponent } from '../balance-display/balance-display.component';
import type { ViewMode } from '../../types';

type TabType = 'deposit' | 'withdraw' | 'balances';

@Component({
    selector: 'nftjuice-widget',
    standalone: true,
    imports: [CommonModule, DepositNftComponent, WithdrawNftComponent, BalanceDisplayComponent],
    templateUrl: './nft-juice-widget.component.html',
    styleUrls: ['../../styles/nft-juice.css'],
    encapsulation: ViewEncapsulation.Emulated
})
export class NftJuiceWidgetComponent implements OnInit, OnDestroy {
    @Input() collectionAddress!: string;
    @Input() view: ViewMode = 'grid';
    @Input() className = '';

    activeTab: TabType = 'deposit';
    collectionInfo: CollectionInfo | null = null;
    isLoading = false;
    errorMessage = '';

    private sdkSubscription?: Subscription;

    constructor(
        public nftJuiceService: NFTJuiceService,
        public walletService: WalletService
    ) {}

    ngOnInit(): void {
        // Subscribe to SDK changes and load collection info when SDK is available
        this.sdkSubscription = this.nftJuiceService.sdk$.subscribe(sdk => {
            if (sdk) {
                this.loadCollectionInfo();
            }
        });
    }

    ngOnDestroy(): void {
        this.sdkSubscription?.unsubscribe();
    }

    async loadCollectionInfo(): Promise<void> {
        const sdk = this.nftJuiceService.currentSdk;
        if (!sdk) return;

        this.isLoading = true;
        this.errorMessage = '';

        try {
            this.collectionInfo = await sdk.getCollectionInfo(this.collectionAddress);
            if (!this.collectionInfo.isAllowed) {
                this.errorMessage = 'This collection is not whitelisted in the NFTJuice system.';
            }
        } catch (err: any) {
            this.errorMessage = err.message || 'Failed to load collection information';
        } finally {
            this.isLoading = false;
        }
    }

    setActiveTab(tab: TabType): void {
        this.activeTab = tab;
    }

    async connectWallet(): Promise<void> {
        try {
            await this.walletService.connectWallet();
        } catch (err) {
            console.error('Failed to connect wallet:', err);
        }
    }

    async switchToNetwork(): Promise<void> {
        try {
            await this.walletService.switchToNetwork('hoodi');
        } catch (err) {
            console.error('Failed to switch network:', err);
        }
    }

    get wallet() {
        return this.walletService.currentWallet;
    }

    get sdk() {
        return this.nftJuiceService.currentSdk;
    }

    get isWrongNetwork(): boolean {
        return this.wallet.isConnected && !!this.sdk && this.wallet.chainId !== this.sdk.currentNetworkConfig.chainId;
    }

    get networkNameToSwitch(): string {
        if (this.sdk && this.wallet.isConnected && this.wallet.chainId) {
            const network = Object.values(NETWORK_CONFIGS).find(c =>
                c.chainId === this.sdk?.currentNetworkConfig.chainId
            );
            return network?.chainName || this.sdk.currentNetworkConfig.chainName || 'correct network';
        }
        return this.sdk?.currentNetworkConfig?.chainName || 'correct network';
    }

    get formattedCollectionAddress(): string {
        return `${this.collectionAddress.slice(0, 6)}...${this.collectionAddress.slice(-4)}`;
    }

    handleTransactionSuccess(result: any): void {
        console.log('Transaction successful:', result);
    }

    handleTransactionError(error: Error): void {
        console.error('Transaction failed:', error);
    }
}

<div [class]="'widget ' + className">
    <div class="header">
        <h2 class="headerTitle">NFTJuice</h2>
        <div class="collectionInfo">
            Collection: {{ formattedCollectionAddress }}
        </div>
    </div>

    <!-- Connect Wallet Section -->
    <div *ngIf="!wallet.isConnected" class="connectSection">
        <div class="message">
            <h3 class="sectionTitle">Connect Your Wallet</h3>
            <p class="sectionDescription">Connect your wallet to start using NFTJuice with this collection.</p>
        </div>
        <button (click)="connectWallet()" class="button">
            Connect Wallet
        </button>
    </div>

    <!-- Wrong Network Section -->
    <div *ngIf="wallet.isConnected && isWrongNetwork" class="networkSection">
        <div class="message">
            <h3 class="sectionTitle">Wrong Network</h3>
            <p class="sectionDescription">
                Please switch to <strong>{{ networkNameToSwitch }}</strong> to use this widget.
            </p>
        </div>
        <button (click)="switchToNetwork()" class="button">
            Switch to {{ networkNameToSwitch }}
        </button>
    </div>

    <!-- Loading Section -->
    <div *ngIf="wallet.isConnected && !isWrongNetwork && isLoading" class="loadingSection">
        <div class="loadingMessage">Loading collection information...</div>
    </div>

    <!-- Error Section -->
    <div *ngIf="wallet.isConnected && !isWrongNetwork && !isLoading && errorMessage" class="errorSection">
        <div class="errorMessage">{{ errorMessage }}</div>
    </div>

    <!-- Main Content -->
    <div *ngIf="wallet.isConnected && !isWrongNetwork && !isLoading && !errorMessage && collectionInfo?.isAllowed">
        <div class="tabs">
            <button
                [class]="'tab' + (activeTab === 'deposit' ? ' active' : '')"
                (click)="setActiveTab('deposit')">
                Deposit
            </button>
            <button
                [class]="'tab' + (activeTab === 'withdraw' ? ' active' : '')"
                (click)="setActiveTab('withdraw')">
                Withdraw
            </button>
            <button
                [class]="'tab' + (activeTab === 'balances' ? ' active' : '')"
                (click)="setActiveTab('balances')">
                Balances
            </button>
        </div>

        <div class="content">
            <nftjuice-deposit-nft
                *ngIf="activeTab === 'deposit'"
                [collectionAddress]="collectionAddress"
                [view]="view"
                (success)="handleTransactionSuccess($event)"
                (error)="handleTransactionError($event)">
            </nftjuice-deposit-nft>

            <nftjuice-withdraw-nft
                *ngIf="activeTab === 'withdraw'"
                [collectionAddress]="collectionAddress"
                [view]="view"
                (success)="handleTransactionSuccess($event)"
                (error)="handleTransactionError($event)">
            </nftjuice-withdraw-nft>

            <nftjuice-balance-display
                *ngIf="activeTab === 'balances'"
                [collectionAddress]="collectionAddress"
                [showAllCollections]="false"
                [view]="view">
            </nftjuice-balance-display>
        </div>
    </div>

    <!-- Collection Not Available -->
    <div *ngIf="wallet.isConnected && !isWrongNetwork && !isLoading && collectionInfo && !collectionInfo.isAllowed" class="errorSection">
        <div class="errorMessage">
            This collection is not available in the NFTJuice system.
        </div>
    </div>
</div>

// packages/react/src/components/NFTJuiceWidget.tsx
import styles from '../styles/NFTJuiceWidget.module.css';

import React, {useState, useEffect, useMemo} from 'react';
import classNames from 'classnames';
import {NETWORK_CONFIGS} from '@nftjuice/sdk'
import type {CollectionInfo} from '@nftjuice/sdk';

import {DepositNFT} from './DepositNFT.js';
import {useNFTJuice} from '../context/NFTJuiceContext.js';
import {WithdrawNFT} from './WithdrawNFT.js';
import {BalanceDisplay} from './BalanceDisplay.js';
import type {NFTJuiceWidgetProps} from '../types.js';


export function NFTJuiceWidget({
                                   collectionAddress,
                                   className = '',
                                   view = 'grid'
                               }: NFTJuiceWidgetProps) {
    const {sdk, wallet, connectWallet, switchToNetwork} = useNFTJuice();
    const [activeTab, setActiveTab] = useState<'deposit' | 'withdraw' | 'balances' | 'exchange'>('deposit');
    const [collectionInfo, setCollectionInfo] = useState<CollectionInfo | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string>('');

    useEffect(() => {
        const loadCollectionInfo = async () => {
            if (!sdk) return;

            setIsLoading(true);
            setError('');

            try {
                const info = await sdk.getCollectionInfo(collectionAddress);
                setCollectionInfo(info);

                if (!info.isAllowed) {
                    setError('This collection is not whitelisted in the NFTJuice system.');
                }
            } catch (err: any) {
                setError(err.message || 'Failed to load collection information');
            } finally {
                setIsLoading(false);
            }
        };

        loadCollectionInfo();
    }, [sdk, collectionAddress]);

    const handleTransactionSuccess = (result: any) => {
        console.log('Transaction successful:', result);
        // Could add toast notifications here
    };

    const handleTransactionError = (error: Error) => {
        console.error('Transaction failed:', error);
        // Could add toast notifications here
    };

    const isWrongNetwork = wallet.isConnected && sdk && wallet.chainId !== sdk.currentNetworkConfig.chainId;

    const networkNameToSwitch = useMemo(() => {
        if (sdk && wallet.isConnected && wallet.chainId) {
            const network = Object.values(NETWORK_CONFIGS).find(c => {
                return c.chainId === sdk.currentNetworkConfig.chainId
            })
            return network?.chainName || sdk.currentNetworkConfig.chainName || 'correct network';
        }
        return sdk?.currentNetworkConfig?.chainName || 'correct network'
    }, [sdk, wallet.chainId, NETWORK_CONFIGS])

    return (
        <div className={classNames(styles.widget, className)}>
            <div className={styles.header}>
                <h2 className={styles.headerTitle}>NFTJuice</h2>
                <div className={styles.collectionInfo}>
                    Collection: {collectionAddress.slice(0, 6)}...{collectionAddress.slice(-4)}
                </div>
            </div>

            {!wallet.isConnected ? (
                <div className={styles.connectSection}>
                    <div className={styles.message}>
                        <h3 className={styles.sectionTitle}>Connect Your Wallet</h3>
                        <p className={styles.sectionDescription}>Connect your wallet to start using NFTJuice with this
                            collection.</p>
                    </div>
                    <button
                        onClick={connectWallet}
                        className={styles.button}
                    >
                        Connect Wallet
                    </button>
                </div>
            ) : isWrongNetwork ? (
                <div className={styles.networkSection}>
                    <div className={styles.message}>
                        <h3 className={styles.sectionTitle}>Wrong Network</h3>
                        <p className={styles.sectionDescription}>Please switch
                            to <strong>{networkNameToSwitch}</strong> to use this widget.</p>
                    </div>
                    <button
                        onClick={() => switchToNetwork('hoodi')}
                        className={styles.button}
                    >
                        Switch to {networkNameToSwitch}
                    </button>
                </div>
            ) : isLoading ? (
                <div className={styles.loadingSection}>
                    <div className={styles.loadingMessage}>Loading collection information...</div>
                </div>
            ) : error ? (
                <div className={styles.errorSection}>
                    <div className={styles.errorMessage}>{error}</div>
                </div>
            ) : collectionInfo && collectionInfo.isAllowed ? (
                <>
                    <div className={styles.tabs}>
                        <button
                            className={classNames(styles.tab, activeTab === 'deposit' && styles.active)}
                            onClick={() => setActiveTab('deposit')}
                        >
                            Deposit
                        </button>
                        <button
                            className={classNames(styles.tab, activeTab === 'withdraw' && styles.active)}
                            onClick={() => setActiveTab('withdraw')}
                        >
                            Withdraw
                        </button>
                        <button
                            className={classNames(styles.tab, activeTab === 'balances' && styles.active)}
                            onClick={() => setActiveTab('balances')}
                        >
                            Balances
                        </button>
                    </div>

                    <div className={styles.content}>
                        {activeTab === 'deposit' && (
                            <DepositNFT
                                collectionAddress={collectionAddress}
                                onSuccess={handleTransactionSuccess}
                                onError={handleTransactionError}
                                view={view}
                            />
                        )}

                        {activeTab === 'withdraw' && (
                            <WithdrawNFT
                                collectionAddress={collectionAddress}
                                onSuccess={handleTransactionSuccess}
                                onError={handleTransactionError}
                                view={view}
                            />
                        )}

                        {activeTab === 'balances' && (
                            <BalanceDisplay
                                collectionAddress={collectionAddress}
                                showAllCollections={false}
                                view={view}
                            />
                        )}
                    </div>
                </>
            ) : (
                <div className={styles.errorSection}>
                    <div className={styles.errorMessage}>
                        This collection is not available in the NFTJuice system.
                    </div>
                </div>
            )}
        </div>
    );
}
